apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: <name>
  template:
    metadata:
      labels:
        name: <name>
    spec:
      nodeSelector:
        env: c1
        db: <nodeLabel>
        kfk: <kfk>
      priorityClassName: class-storage
      initContainers:
        - name: init-dir
          image: busybox
          volumeMounts:
            - name: vol-data
              mountPath: /pam/<namespace>/<name>
          command: ["/bin/sh", "-c", "chown 1001 /pam/<namespace>/<name>"]
      containers:
      - name: <name>
        image: 3dsinteractive/kafka:2.0-custom
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ID
          value: <kafkaBrokerID>
        - name: KAFKA_PORT_NUMBER
          value: <kafkaPortNumber>
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://<name>:9092
        - name: KAFKA_LISTENERS
          value: INSIDE://:9092
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_NUM_PARTITIONS
          value: <kafkaNumPartitions>
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: <kafkaZookeeperConnect>
        - name: KAFKA_NUM_NETWORK_THREADS
          value: <kafkaNumNetworkThreads>
        - name: KAFKA_NUM_IO_THREADS
          value: <kafkaNumIOThreads>
        - name: KAFKA_SOCKET_SEND_BUFFER_BYTES
          value: <kafkaSocketSendBuffeBytes>
        - name: KAFKA_SOCKET_RECEIVE_BUFFER_BYTES
          value: <kafkaSocketReceiveBufferBytes>
        - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
          value: <kafkaSocketRequestMaxBytes>
        - name: KAFKA_MAX_MESSAGE_BYTES
          value: <kafkaMaxMessageBytes>
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_HEAP_OPTS
          value: <kafkaHeapOpts>
        resources:
          requests:
            memory: <minMem>
            cpu: <minCpu>
          limits:
            memory: <maxMem>
            cpu: <maxCpu>
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        ports:
        - containerPort: 9092
          name: kfk9092
        volumeMounts:
        - mountPath: /bitnami/kafka
          name: vol-data
      volumes:
      - name: vol-data
        persistentVolumeClaim:
          claimName: pvc-<name>
---
apiVersion: v1
kind: Service
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  selector:
    name: <name>
  ports:
  - name: kfk9092
    port: 9092
    protocol: TCP
  clusterIP: None