apiVersion: batch/v1
kind: Job
metadata:
  name: <name>
  namespace: <namespace>
spec:
  ttlSecondsAfterFinished: 180
  template:
    spec:
      imagePullSecrets:
      - name: dockerlogin
      restartPolicy: Never
      containers:
      - name: <name>
        image: 3dsinteractive/pam4-cmsseeder:<namespace>-6.0.<timestamp>
        imagePullPolicy: Always
        env: [ {name: PAM4_ENV, value: prod}, {name: DEBUG, value: "true"} <envs>]