apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  replicas: 1
  selector:
    matchLabels:
      name: <name>
  template:
    metadata:
      labels:
        name: <name>
    spec:
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
      - name: dockerlogin
      nodeSelector:
        env: c1
        role: worker
      containers:
      - name: <name>
        image: 3dsinteractive/pam4-cmsseeder:<tag>.<timestamp>
        imagePullPolicy: Always
        env: [ {name: PAM4_ENV, value: prod}, {name: DEBUG, value: "true"} <envs>]