apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  replicas: 1
  selector:
    matchLabels:
      name: <name>
  template:
    metadata:
      labels:
        name: <name>
    spec:
      imagePullSecrets:
      - name: dockerlogin
      nodeSelector:
        env: c1
        role: worker
      containers:
        - name: <name>
          image: 3dsinteractive/pam-migrate-ecom:<tag>.<timestamp>
          imagePullPolicy: Always
          env: [ {name: PAM4_ENV, value: prod}, {name: DEBUG, value: "true"} <envs>]
          readinessProbe:
            httpGet:
              path: /readinez
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 10
          ports:
          - name: probe8080
            containerPort: 8080
          resources:
            requests:
              memory: <minMem>
              cpu: <minCpu>
            limits:
              memory: <maxMem>
              cpu: <maxCpu>
---
apiVersion: v1
kind: Service
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  ports:
  - port: 8080
    name: probe8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: <name>