{
 "title": "Servers",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RAM Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(100, 100 -\n(\n  node_memory_MemAvailable_bytes{job=\"prometheus-node-exporter\"}\n/\n  node_memory_MemTotal_bytes{job=\"prometheus-node-exporter\"}\n* 100\n))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cached Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(100, \n(\n  node_memory_Cached_bytes{job=\"prometheus-node-exporter\"}\n/\n  node_memory_MemTotal_bytes{job=\"prometheus-node-exporter\"}\n* 100\n))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(100, 1 - avg(rate(node_cpu_seconds_total{job=\"prometheus-node-exporter\", mode=\"idle\"}[5m])) by (instance))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Used by CORE %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(100, 1 - rate(node_cpu_seconds_total{job=\"prometheus-node-exporter\", mode=\"idle\"}[5m]))\n",
     "legendFormat": "{{instance}} (core {{cpu}})"
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(100, \n100 * (\n   (node_filesystem_size_bytes{job=\"prometheus-node-exporter\", fstype!=\"\"} - \n    node_filesystem_avail_bytes{job=\"prometheus-node-exporter\", fstype!=\"\"})\n    /\n   node_filesystem_size_bytes{job=\"prometheus-node-exporter\", fstype!=\"\"}\n )\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "topk(100, irate(node_disk_reads_completed_total{job=\"prometheus-node-exporter\"}[5m]))",
     "legendFormat": "{{instance}} - Reads"
    },
    {
     "expr": "topk(100, irate(node_disk_writes_completed_total{job=\"prometheus-node-exporter\"}[5m]))",
     "legendFormat": "{{instance}} - Writes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=~\"prometheus-node-exporter\"} [5m])",
     "legendFormat": "{{instance}} - I/Os time"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"prometheus-node-exporter\"}[5m])",
     "legendFormat": "{{instance}} - read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"prometheus-node-exporter\"}[5m])",
     "legendFormat": "{{instance}} - write bytes"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{job=~\"prometheus-node-exporter\"}[5m]))*8",
     "legendFormat": "{{instance}} - recv"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{job=~\"prometheus-node-exporter\"}[5m]))*8",
     "legendFormat": "{{instance}} - send"
    }
   ]
  }
 ]
}