apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
  namespace: <namespace>
  labels:
    app: monitor
    name: grafana-dashboards-provider
data:
  providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'PAM'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards