{
 "title": "K8S Pods",
 "description": "K8S Pods Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Pods status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"<namespace>\"})"
    }
   ]
  },
  {
   "title": "Pods Restarts Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"<namespace>\"})"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "topk(100, sum(kube_pod_container_status_restarts_total{namespace=\"<namespace>\"}) by (pod)) > 0"
    }
   ]
  },
  {
   "title": "Memory Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "topk(100, sum(kube_pod_container_resource_requests{namespace=\"<namespace>\", resource=\"memory\"}) by (pod))"
    },
    {
     "expr": "topk(100, sum(kube_pod_container_resource_limits{namespace=\"<namespace>\", resource=\"memory\"})  by (pod))"
    }
   ]
  },
  {
   "title": "CPU Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "topk(100, sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"<namespace>\"}) by (pod))"
    },
    {
     "expr": "topk(100, sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", namespace=\"<namespace>\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Pods Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"<namespace>\"})",
     "legendFormat": "Pods Count"
    }
   ]
  },
  {
   "title": "Pods Restarts Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"<namespace>\"})",
     "legendFormat": "Pods Restart Count"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory by Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum(kube_metrics_server_pods_mem{pod_namespace=\"<namespace>\"}) by (pod_container_name) )",
     "legendFormat": "{{pod_container_name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU by Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "m" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum(kube_metrics_server_pods_cpu{pod_namespace=\"<namespace>\"}) by (pod_container_name) )",
     "legendFormat": "{{pod_container_name}}"
    }
   ]
  }
 ]
}