{
 "title": "Golang",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(go_goroutines{job=\"seaman-metric\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mem Allocated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(go_memstats_alloc_bytes{job=\"seaman-metric\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Open FDS (files, sockets)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(process_open_fds{job=\"seaman-metric\"})",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}