apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  namespace: <namespace>
  labels:
    app: monitor
    name: prom-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 20s
      scrape_timeout: 20s

    alerting:
      alertmanagers:
      - scheme: http
        static_configs: 
        - targets:
          - "prom-alert1:9093"

    rule_files:
    - '/etc/alert-rules/*.rules'

    scrape_configs:
    
    - job_name: metrics-server
      metrics_path: /metrics
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (metrics-server-exporter-.*?)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace

    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: 
          - "kube-state-metrics:8080"

    - job_name: redis-metric
      metrics_path: /metrics
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (prom-redis-exporter-.*?)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
    
    - job_name: els-metric
      metrics_path: /metrics
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (prom-els-exporter-.*?)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace

    - job_name: kafka-metric
      metrics_path: /metrics
      scrape_interval: 120s
      scrape_timeout: 60s
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (prom-kafka-exporter-.*?)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace

    - job_name: maria-cms-metric
      metrics_path: /metrics
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (prom-maria-cms-exporter-.*?)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace

    - job_name: maria-connect-metric
      metrics_path: /metrics
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (prom-maria-connect-exporter-.*?)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace

    - job_name: seaman-metric
      metrics_path: /metrics
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (<monitorServices>)
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace

    - job_name: node-exporter
      honor_timestamps: true
      metrics_path: /metrics
      scheme: http
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - <namespace>
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_name]
        separator: ;
        regex: prometheus-node-exporter
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Pod;(.*)
        target_label: pod
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: job
        replacement: ${1}
        action: replace