{
 "title": "Elasticsearch Query",
 "description": "Dashboard to view metrics of elasticsearch_exporter on each elasticsearch servers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(elasticsearch_process_cpu_percent{cluster=\"$cluster\"},name)"
   }
  ]
 },
 "panels": [
  { "title": "Query Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_status{cluster=\"$cluster\", color=\"green\"}) * 3\n+\navg(elasticsearch_cluster_health_status{cluster=\"$cluster\", color=\"yellow\"}) * 2\n+\navg(elasticsearch_cluster_health_status{cluster=\"$cluster\", color=\"red\"}) * 1"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_number_of_data_nodes{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Shards",
   "type": "singlestat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards.",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Primary Shards",
   "type": "singlestat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_active_primary_shards{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Init-ing Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Delayed Unassigned Shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "singlestat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(elasticsearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\", name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Query cache hit/miss",
   "type": "graph",
   "description": "Count of query cache hit/miss",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_query_cache_count{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name, cache)",
     "legendFormat": "{{ name }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Query cache usage",
   "type": "graph",
   "description": "Query cache memory usage in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Request cache hit/miss",
   "type": "graph",
   "description": "Count of request cache hit/miss",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_request_cache_count{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name, cache)",
     "legendFormat": "{{ name }} {{ cache }}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "graph",
   "description": "Size of query cache",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_cache_size{cluster=~\"$cluster\", name=~\"$node\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Request cache evictions",
   "type": "graph",
   "description": "Evictions from request cache",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_request_cache_evictions{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "graph",
   "description": "Evictions from query cache",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])\nor\nirate(elasticsearch_indices_query_cache_evictions{cluster=~\"$cluster\", name=~\"$node\"}[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Search Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_search_query_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))",
     "legendFormat": "query"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))",
     "legendFormat": "fetch"
    }
   ]
  },
  {
   "title": "Get Latencies",
   "type": "graph",
   "description": "Average get time in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_get_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) \nor\nsum(irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)  / sum(irate(elasticsearch_indices_get_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) ",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Indexing Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))\nor\nsum(irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) / sum(irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$node\"}[5m]))",
     "legendFormat": "index"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))\nor\nsum(irate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) / sum(irate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\", name=~\"$node\"}[5m]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Merges",
   "type": "graph",
   "description": "Average merge size in bytes and time spent merging in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_merges_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) / sum(irate(elasticsearch_indices_merges_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)",
     "legendFormat": "{{ name }} time"
    },
    {
     "expr": "sum(rate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_merges_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_indices_merges_total_size_bytes_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) / sum(irate(elasticsearch_indices_merges_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)",
     "legendFormat": "{{ name }} size"
    }
   ]
  },
  {
   "title": "Flush",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) / sum(rate(elasticsearch_indices_flush_total\t{cluster=\"$cluster\", name=~\"$node\"}[$__interval]))\nor\nsum(irate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\", name=~\"$node\"}[5m])) / sum(irate(elasticsearch_indices_flush_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m]))",
     "legendFormat": "flush"
    }
   ]
  },
  {
   "title": "Refresh",
   "type": "graph",
   "description": "Average time spent refreshing in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name) / sum(rate(elasticsearch_indices_refresh_total\t{cluster=\"$cluster\", name=~\"$node\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name) / sum(irate(elasticsearch_indices_refresh_total\t{cluster=\"$cluster\", name=~\"$node\"}[5m])) by (name)",
     "legendFormat": "refresh"
    }
   ]
  },
  {
   "title": "Machine Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage 5m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time(elasticsearch_process_cpu_percent{cluster=~\"$cluster\", name=~\"$node\"}[5m])",
       "legendFormat": "{{ name }}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "failure_tstamp"
      }
     ]
    },
    {
     "title": "JVM heap memory used",
     "type": "graph",
     "description": "JVM heap memory currently used by area",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_used_bytes{cluster=~\"$cluster\", name=~\"$node\", area=\"heap\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "JVM heap memory committed",
     "type": "graph",
     "description": "JVM heap memory currently committed by area",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_jvm_memory_committed_bytes{cluster=~\"$cluster\", name=~\"$node\", area=\"heap\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Average Heap in 1min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(elasticsearch_jvm_memory_used_bytes{area=\"heap\", cluster=~\"$cluster\", name=~\"$node\"}[1m]) / elasticsearch_jvm_memory_max_bytes{area=\"heap\", cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "GC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC rate (young)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[$__interval])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "GC rate (old)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[$__interval])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "GC seconds (young)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[$__interval])) by (name) / sum(rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[5m])) by (name) / sum(irate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"young\"}[5m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "GC seconds (old)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[$__interval])) by (name) / sum(rate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[$__interval])) by (name)\nor\nsum(irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[5m])) by (name) / sum(irate(elasticsearch_jvm_gc_collection_seconds_count{cluster=~\"$cluster\", name=~\"$node\", gc=\"old\"}[5m])) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Segments Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Segments Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_memory_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Breaker Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Breaker",
     "type": "graph",
     "description": "Estimated size in percent of breaker",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_breakers_estimated_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}) by (breaker) / sum(elasticsearch_breakers_limit_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}) by (breaker)",
       "legendFormat": "{{ breaker }}"
      }
     ]
    },
    {
     "title": "Breaker tripped",
     "type": "graph",
     "description": "tripped for breaker",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(elasticsearch_breakers_tripped{cluster=~\"$cluster\", name=~\"$node\"}[$__interval])) by (name, breaker)",
       "legendFormat": "{{ name }} {{ breaker }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual memory",
     "type": "graph",
     "description": "Total virtual memory used in bytes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_mem_virtual_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "graph",
     "description": "Open file descriptors",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "elasticsearch_process_open_files_count{cluster=~\"$cluster\", name=~\"$node\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Disk Free",
     "type": "graph",
     "description": "Used size of block device in percent",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(elasticsearch_filesystem_data_free_bytes{cluster=~\"$cluster\", name=~\"$node\"}) by (name) / sum(elasticsearch_filesystem_data_size_bytes{cluster=~\"$cluster\", name=~\"$node\"}) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  }
 ]
}