{
 "title": "PAM Summary",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP GET (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_http_request_total{method=\"get\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "HTTP GET (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_http_process_time_seconds_sum{method=\"get\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_http_request_total{method=\"get\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "HTTP GET (Error/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_http_error_total{method=\"get\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "HTTP POST/PUT (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_http_request_total{method=~\"post|put\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "HTTP POST/PUT (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_http_process_time_seconds_sum{method=~\"post|put\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_http_request_total{method=~\"post|put\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "HTTP POST/PUT (Error/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_http_error_total{method=~\"post|put\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer / Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_consumer_request_total{method=\"consume\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Consumer (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_consumer_process_time_seconds_sum{method=\"consume\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_consumer_request_total{method=\"consume\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Producer (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_producer_request_total{method=\"send\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Producer (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_producer_process_time_seconds_sum{method=\"send\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_producer_request_total{method=\"send\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  { "title": "Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Indexer GET (Count/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_request_total{method=\"get\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer GET (Time/Request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(100, (sum(rate(seaman_indexer_process_time_seconds_sum{method=\"get\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_indexer_request_total{method=\"get\"}[5m])) by (endpoint) ))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer GET (Error/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_error_total{method=\"get\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer POST (Count/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_request_total{method=~\"post\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer POST (Time/Request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(100, (sum(rate(seaman_indexer_process_time_seconds_sum{method=~\"post\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_indexer_request_total{method=~\"post\"}[5m])) by (endpoint) ))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer POST (Error/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_error_total{method=~\"post\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer PUT (Count/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_request_total{method=~\"put\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer PUT (Time/Request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(100, (sum(rate(seaman_indexer_process_time_seconds_sum{method=~\"put\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_indexer_request_total{method=~\"put\"}[5m])) by (endpoint) ))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer PUT (Error/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_error_total{method=~\"put\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer Aggs (Count/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_request_total{method=\"aggs\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer Aggs (Time/Request)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(100, (sum(rate(seaman_indexer_process_time_seconds_sum{method=\"aggs\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_indexer_request_total{method=\"aggs\"}[5m])) by (endpoint) ))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Indexer Aggs (Error/Minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum( rate(seaman_indexer_error_total{method=~\"aggs\"}[5m]) ) by (endpoint) * 60 )",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requester GET (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_requester_request_total{method=~\"get\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Requster GET (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_requester_process_time_seconds_sum{method=~\"get\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_requester_request_total{method=~\"get\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Requester GET (Error/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_requester_error_total{method=~\"get\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Requester POST/PUT (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_requester_request_total{method=~\"post|put\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Requster POST/PUT (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_requester_process_time_seconds_sum{method=~\"post|put\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_requester_request_total{method=~\"post|put\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Requester POST/PUT (Error/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_requester_error_total{method=~\"post|put\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cacher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cacher GET (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_cacher_request_total{method=\"get\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Cacher GET (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_cacher_process_time_seconds_sum{method=\"get\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_cacher_request_total{method=\"get\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Cacher SET (Count/Minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100, sum( rate(seaman_cacher_request_total{method=\"set\"}[5m]) ) by (endpoint) * 60 )",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Cacher SET (Time/Request)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(100, (sum(rate(seaman_cacher_process_time_seconds_sum{method=\"set\"}[5m])) by (endpoint) * 1000) / \n(sum(rate(seaman_cacher_request_total{method=\"set\"}[5m])) by (endpoint) ))",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}