apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-kafka-exporter
  namespace: <namespace>
  labels:
    name: prom-kafka-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: prom-kafka-exporter
  template:
    metadata:
      labels:
        name: prom-kafka-exporter
    spec:
      nodeSelector:
        env: c1
        role: worker
      priorityClassName: class-monitor
      containers:
      - name: prom-kafka-exporter
        image: 3dsinteractive/kafka-minion:1.0.0
        imagePullPolicy: Always
        env:
          - name: KAFKA_BROKERS
            value: kfk1:9092,kfk2:9092,kfk3:9092
          - name: KAFKA_VERSION
            value: "2.0.0"
          - name: KAFKA_SASL_ENABLED
            value: "false"
          - name: KAFKA_TLS_ENABLED
            value: "false"
          - name: TELEMETRY_PORT
            value: "8080"
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 500Mi
            cpu: 300m
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        ports:
        - containerPort: 8080
          name: exporter8080
---
apiVersion: v1
kind: Service
metadata:
  name: prom-kafka-exporter
  namespace: <namespace>
  labels:
    name: prom-kafka-exporter
spec:
  ports:
  - port: 9308
    name: "exporter9308"
    targetPort: 8080
    protocol: TCP
  selector:
    name: prom-kafka-exporter