apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    app: monitor
    name: <name>
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: <name>
  template:
    metadata:
      labels:
        name: <name>
    spec:
      serviceAccountName: prometheus
      nodeSelector:
        env: c1
        monitor: <nodeLabel>
      priorityClassName: class-monitor
      containers:
      - name: <name>
        image: 3dsinteractive/prometheus:2.0
        ports:
        - name: prometheus9090
          containerPort: 9090
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 300m
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        volumeMounts:
        - mountPath: /opt/bitnami/prometheus/conf
          name: vol-config
        - mountPath: /etc/alert-rules
          name: vol-config-alert-rules
      volumes:
      - name: vol-config
        configMap:
          name: prom-config
      - name: vol-config-alert-rules
        configMap:
          name: prom-alert-rules
---
apiVersion: v1
kind: Service
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    app: monitor
    name: prometheus
spec:
  selector:
    name: <name>
  ports:
  - port: 9090
    name: prometheus9090
    targetPort: 9090
    protocol: TCP