{
 "title": "MariaDB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Query/Second",
   "type": "graph",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{}[5m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max by (service) (max_over_time(mysql_global_status_threads_connected{}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (service) (rate(mysql_global_status_slow_queries{}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5, rate(mysql_global_status_commands_total{}[5m])>0) by (service, command)",
     "legendFormat": "{{ service }} {{ command }}"
    }
   ]
  }
 ]
}