{
 "title": "Alerts",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (container, reason) (sum_over_time(kube_pod_container_status_terminated_reason{reason=~\"(Error|Evicted|OOMKilled|ContainerCannotRun|DeadlineExceeded)\"}[1h])) > 0",
     "legendFormat": "{{container}} ({{reason}})"
    }
   ]
  },
  {
   "title": "Service Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, service, endpoint) (increase(seaman_error_request_total{}[5m])) > 0",
     "legendFormat": "{{service}} ({{endpoint}})"
    }
   ]
  },
  {
   "title": "Topic Lags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (group, topic) (avg_over_time(kafka_minion_group_topic_lag{group=~\"<topicsInclude>\", topic!=\"<topicsExclude>\"}[1h])) > 1",
     "legendFormat": "{{group}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Slow HTTP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, endpoint) (rate(seaman_http_process_time_seconds_sum{endpoint!~\"/ptask/.*?\"}[5m]) ) / sum by (namespace, endpoint) (rate(seaman_http_process_time_seconds_count{endpoint!~\"/ptask/.*?\"}[5m]))) > 2",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Slow Consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, endpoint) (rate(seaman_consumer_process_time_seconds_sum{}[5m]) ) / sum by (namespace, endpoint) (rate(seaman_consumer_process_time_seconds_count{}[5m]))) > 5",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}