apiVersion: v1
kind: ConfigMap
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    app: monitor
    name: <name>
data:
  providers.yaml: |
    apiVersion: 1
    datasources:
    - name: 'Prometheus'
      type: prometheus
      access: proxy
      orgId: 1
      url: <promURL>
      isDefault: true
      editable: true