apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-els1
  namespace: <namespace>
  labels:
    name: pv-els1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pam/<namespace>/els1/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-els2
  namespace: <namespace>
  labels:
    name: pv-els2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pam/<namespace>/els2/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-els3
  namespace: <namespace>
  labels:
    name: pv-els3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pam/<namespace>/els3/data
---