apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
  namespace: <namespace>
  labels:
    name: pv-minio
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pam/<namespace>/minio/data