apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-<name>
  namespace: <namespace>
  labels:
    name: pv-<name>
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pam/<namespace>/<name>/data