apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  namespace: <namespace>
  labels:
    name: pv-redis
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pam/<namespace>/redis/data