apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio
  namespace: <namespace>
  labels:
    name: pvc-minio
spec:
  volumeName: pv-minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi