apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: <namespace>
  labels:
    name: kibana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: kibana
  template:
    metadata:
      labels:
        name: kibana
    spec:
      nodeSelector:
        env: c1
        role: worker
      priorityClassName: class-monitor
      containers:
      - name: kibana
        image: 3dsinteractive/kibana:6.8
        imagePullPolicy: Always
        env:
        - name: KIBANA_ELASTICSEARCH_URL
          value: <elsUrl>
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 500Mi
            cpu: 300m
        livenessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 5601
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 30
          failureThreshold: 5
        ports:
        - containerPort: 5601
          name: kibana5601